#:schema https://www.schemastore.org/cargo.json

[workspace]
members = [".", "test_helpers"]

[package]
name = "trident"
version = "0.1.0"
edition = "2024"
description = "The all-in-one DevEx tool."

[dependencies]
ahash = { version = "0.8.12", features = ["serde"] }
big_s = "1.0.2"
clap = { version = "4.6.4", features = ["derive"] }
conc = { package = "concurrent_shell_commands", version = "0.10.1" }
ignore = "0.4.31"
itertools = "0.14.0"
jsonc-parser = { version = "0.33.1", features = ["serde"] }
rta = { package = "run-that-app", version = "0.42.6" }
schemars = { version = "1.2.2", features = ["preserve_order"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_with = "3.21.0"
shlex = "2.0.1"
strum = { version = "0.28.0", features = ["derive"] }
which = "8.0.5"

[dev-dependencies]
contains_lines = "0.0.2"
cucumber = "0.23.0"
itertools = "0.14.0"
maplit = "1.0.2"
mio = "1.2.2"
pretty = { package = "pretty_assertions", version = "1.4.1" }
rand = "0.10.2"
regex = "1.13.1"
serde_json = "1.0.151"
strip-ansi-escapes = "0.2.1"
tempfile = "3.27.0"
test_helpers = { path = "test_helpers" }
tokio = { version = "1.53.1", features = [
  "fs",
  "io-util",
  "macros",
  "process",
  "rt",
  "time",
] }

[[test]]
name = "cuke"   # the filename of the test
harness = false # allows Cucumber to print output instead of libtest
test = false    # don't run this as part of "cargo test"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
into_iter_without_iter = "allow"
similar_names = "allow"

[lints.rust]
unsafe_code = "forbid"
